server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : https://eureka.gaenari.kr/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allow-credentials: true
            allowedHeaders: '*'
            exposedHeaders: '*'
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: member-service
          uri: http://member-service.member.svc.cluster.local
          predicates:
            - Path=/api/member-service/login/**, /api/member-service/members/**, /api/member-service/logout/**, /api/member-service/v3/api-docs/**, /api/member-service/health_check
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: http://member-service.member.svc.cluster.local
          predicates:
            - Path=/api/member-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/member-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: inventory-service
          uri: http://inventory-service.inventory.svc.cluster.local
          predicates:
            - Path=/api/inventory-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/inventory-service/(?<path>.*), /$\{path}
        - id: program-service
          uri: http://program-service.program.svc.cluster.local
          predicates:
            - Path=/api/program-service/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/program-service/(?<segment>.*), /$\{segment}
        - id: program-service
          uri: http://program-service.program.svc.cluster.local
          predicates:
            - Path=/api/program-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/program-service/(?<path>.*), /$\{path}
        - id: exercise-record-service
          uri: http://exercise-record-service.exercise-record.svc.cluster.local
          predicates:
            - Path=/api/exercise-record-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/exercise-record-service/(?<path>.*), /$\{path}
        - id: challenge-service
          uri: http://challenge-service.challenge.svc.cluster.local
          predicates:
            - Path=/api/challenge-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/challenge-service/(?<path>.*), /$\{path}

springdoc:
  swagger-ui:
    use-root-path: true
    urls[0]:
      name: 멤버 서비스
      url: https://api.gaenari.kr/api/member-service/v3/api-docs
    urls[1]:
      name: 프로그램 서비스
      url: https://api.gaenari.kr/api/program-service/v3/api-docs
    urls[2]:
      name: 운동 기록 서비스
      url: https://api.gaenari.kr/api/exercise-record-service/v3/api-docs
    urls[3]:
      name: 도전과제 서비스
      url: https://api.gaenari.kr/api/challenge-service/v3/api-docs
    urls[4]:
      name: 인벤토리 서비스
      url: https://api.gaenari.kr/api/inventory-service/v3/api-docs

token:
  expiration_time: 86400000 # 60*60*24*1000
  secret: member_token_dskjlhfahgiuohauiorheoaihishsodjsafpofjdoadspdoiajfsoisajfdio # 임의의 값